baseURL: https://www.benwilsonwrites.com/
languageCode: en-us
title: Ben C Wilson
theme: hugo-merovex-2021
permalinks:
  post: "/post/:slug"
build:
  writeStats: true
taxonomies:
  series: series
  book: book
  tag: tag
  category: category

params:
  cdn_url: https://d1czp97ry8if6j.cloudfront.net
  subtitle: Writes
  venue: Virginia
  icons:
    kindle: fas fa-tablet-alt
    audible: fab fa-audible
    paperback: far fa-book
    nobel: fas fa-typewriter
  buttons:
    kindle: bg-blue-600 text-white
    audible: bg-yellow-600 text-white
    paperback: bg-black text-white
    nobel: bg-green-600 text-white
  licenses:
    CC0:
      tag: "CC0"
      url: "https://creativecommons.org/share-your-work/public-domain/cc0/"
    PD:
      tag: "Public Domain"
      url: "https://creativecommons.org/share-your-work/public-domain/cc0/"
    RR:
      tag: "Rights Reserved"
      url: "#"
    BY:
      tag: "CC BY 2.0"
      url: "https://creativecommons.org/licenses/by/2.0/"
    BY-SA:
      tag: "CC BY-SA 2.0"
      url: "https://creativecommons.org/licenses/by-sa/2.0/"
    BY-ND:
      tag: "CC BY-ND 2.0"
      url: "https://creativecommons.org/licenses/by-nd/2.0/"