#!/Users/merovex/.rvm/rubies/ruby-2.7.1/bin/ruby

require 'securerandom'
puts SecureRandom.uuid.split('-').first

Dir.glob("content/posts/**/index.md").each do |post|
  a = "aliases: ['/p/#{SecureRandom.uuid.split('-').first}']"
  f = File.open(post,'r')
  c = f.read().gsub(/\A---/, "---\naliases: ['/p/#{SecureRandom.uuid.split('-').first}']")
  f.close
  f = File.open(post, 'w')
  f.write(c)
  f.close
  # raise post.inspect
  puts post
end
