const adjectives = {
  absolute: "absoluta",
  aged: "malyuna",
  ancient: "antikva",
  autumn: "autuno",
  beautiful: "bela",
  believing: "kreda",
  billowing: "blovado",
  bitter: "akra",
  black: "negra",
  blue: "blua",
  bold: "audaca",
  broken: "disrompita",
  capable: "kapabla",
  cold: "malvarma",
  complicated: "komplika",
  cool: "malvarmeta",
  crimson: "karmezina",
  damp: "malseka",
  dark: "malhela",
  debating: "debata",
  delicate: "delikata",
  devilish: "diabla",
  diverse: "diversa",
  divine: "devina",
  dry: "seka",
  dutiful: "obema",
  empty: "malplena",
  evening: "vespera",
  extensive: "ampleska",
  falling: "falanta",
  fearful: "tima",
  floral: "flora",
  forgetful: "forgesa",
  foxy: "vulpa",
  fragrant: "bonodora",
  frequent: "ofta",
  friendly: "amika",
  frosty: "frosta",
  giving: "donaca",
  green: "verda",
  handy: "proksima",
  happy: "felicha",
  hidden: "kasha",
  holy: "sankta",
  icy: "glacia",
  late: "malfrua",
  lingering: "kronika",
  little: "malgranda",
  lively: "viva",
  long: "longa",
  misty: "misty",
  morning: "matena",
  muddy: "kota",
  nameless: "anonima",
  necessary: "necesa",
  nomadic: "nomada",
  old: "malnova",
  patient: "pacienca",
  peachy: "persika",
  polished: "jentila",
  precise: "preciza",
  proud: "fiera",
  purple: "purpura",
  quaint: "charma",
  quiet: "kvieta",
  ravenous: "englutema",
  red: "ruja",
  regretful: "bedaura",
  restless: "malkvieta",
  rough: "kruda",
  savage: "sovaja",
  sensible: "senca",
  shy: "timida",
  silent: "silenta",
  skillful: "lerta",
  small: "malgranda",
  snowy: "neja",
  solitary: "sola",
  sparkling: "brileta",
  spring: "printempa",
  still: "trankvila",
  summer: "somera",
  terrible: "terura",
  thankful: "danka",
  thinking: "pensa",
  throbbing: "pulsa",
  tranquil: "trankvila",
  twilight: "krepuska",
  vigorous: "vigla",
  wandering: "vagada",
  weathered: "eluzita",
  weeping: "plora",
  white: "blanka",
  wild: "frenza",
  winter: "vintra",
  wispy: "maldika",
  withered: "velka",
  yellow: "flava",
  young: "yuna",
  heedless: "senatenta",
};
const nouns = {
  amusement: "amuzo",
  basket: "korbo",
  belief: "kredo",
  bird: "birdo",
  breeze: "venteto",
  brook: "rivereto",
  bush: "arbedo",
  butterfly: "papilio",
  cherry: "cherizo",
  cloud: "nubo",
  darkness: "mallumo",
  dawn: "krepusko",
  debate: "debato",
  desire: "deziro",
  devil: "diablo",
  dew: "roso",
  dream: "sonjo",
  dust: "polvo",
  existence: "ekzisto",
  feather: "plumo",
  field: "kampo",
  fire: "brulego",
  firefly: "lampiro",
  flower: "floro",
  fog: "nebulo",
  forest: "arbaro",
  fox: "vulpo",
  friend: "amiko",
  frog: "rano",
  frost: "prujno",
  gift: "donaco",
  glade: "arbarkampo",
  glitter: "brilo",
  goal: "celo",
  grass: "herbo",
  hand: "mano",
  haze: "nebuleto",
  hill: "monto",
  horse: "chevalo",
  lake: "lago",
  leaf: "folio",
  meadow: "herbejo",
  moon: "luno",
  morning: "mateno",
  mountain: "mateno",
  night: "nokto",
  paper: "papero",
  peach: "persiko",
  pine: "pino",
  precision: "precizo",
  rain: "pluvo",
  regret: "bedauro",
  resonance: "resonanco",
  river: "rivero",
  sea: "maro",
  shadow: "ombro",
  shape: "formo",
  silence: "kvieto",
  situation: "situacio",
  sky: "chielo",
  smoke: "fumo",
  snow: "nejo",
  snowflake: "nejero",
  sound: "sono",
  star: "stelo",
  story: "rakonto",
  sun: "suno",
  sunset: "sunsubiro",
  surf: "shaumo",
  thanks: "danko",
  thunder: "tondro",
  tree: "arbo",
  valor: "kurajo",
  violet: "violo",
  voice: "vocho",
  watchtower: "gardoturo",
  water: "akvo",
  waterfall: "akvofalo",
  wave: "ondo",
  wind: "vento",
  wizard: "sorcho",
  wood: "ligno",
};

var getRandom = function (arr, myrng) {
  var keys = Object.keys(arr)
  return keys[Math.floor(myrng() * keys.length)]
}

var haiku = function () {
  var myrng = new Math.seedrandom(Math.random().toString(36));
  // var myrng = Math.random;
  const number = Math.floor(myrng() * ((9999 + 1) - 1000)) + 1000;

  const adj_en = getRandom(adjectives, myrng);
  const noun_en = getRandom(nouns, myrng);

  const adj_es = adjectives[adj_en]
  const noun_es = nouns[noun_en]

  var esperanto = adj_es + '-' + noun_es + '-' + number
  var english = adj_en + '-' + noun_en + '-' + number

  return [english, esperanto];
};

var updateTargetWithHaiku = function () {
  var h = haiku();
  $('#terms').fadeOut(0);

  $('#heroku').text(h[0]);
  $('#heroko').text(h[1]);
  $('#terms').fadeIn(300);

};
